### ISSUE TITLE
Does this still evolve, how about http://emailjs.org/

### ISSUE THREAD

**Issue by lygstate** [mozilla-comm/jsmime#12]

**Comment by lygstate** [comment]
I wanaa to getting jsmime to implement mbox file's displayMessage.

**Comment by jcranmer** [comment]
Yes, this is still in active development. I just finished backporting all of the changes.

I'm aware of emailjs.org, but their utilities have generally been subpar (with more emphasis on "get something working" than "get something right"--note the sort of bugs that have accumulated due to use in a large application).
